var ForumConstants = {
    FORUM_ANSWER_ADDED: 'FORUM_ANSWER_ADDED',
    FORUM_ANSWER_MARKED_CORRECT: 'FORUM_ANSWER_MARKED_CORRECT',
    FORUM_ANSWER_DELETED: 'FORUM_ANSWER_DELETED'
};

module.exports = ForumConstants;